name = "logs_morgangallant_com"
type = "webpack"
account_id = "bebab53f5a3687bd363b9f59f05b7eb2"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

# Production KV Namespace
kv_namespaces = [ 
	 { binding = "LDB", id = "add145f159ff4fa1bb320d2589065048" }
]
